### ISSUE TITLE
Authorize DCA and P2P managers as vault protocols - avalanche

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#115]
# Description

Authorize the new DCA and P2P manager contracts as protocols in CaskVault so they can perform payments.

* CaskDCAManager (`0xdb78923D5F7381143c16d57E474bCB5c939Df5DE`)
* CaskP2PManager (`0x781a5958954a10066feB7B3E94D22D9F8c163e8b`)

# Transaction Target

CaskVault: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`

# Transaction List

addProtocol
* protocol: `0xdb78923D5F7381143c16d57E474bCB5c939Df5DE`

addProtocol
* protocol: `0x781a5958954a10066feB7B3E94D22D9F8c163e8b`

# Post execution confirmation code

`yarn hardhat debug --network mainnet_avalanche`

Confirmation:
* Confirm new manager contract addresses appear in the vault protocols list.

**Comment by masha256** [comment]
safe nonce 7

**Comment by masha256** [comment]
transaction 7 is invalid - the transaction has to go through the timelock controller. Will open a new ticket.

**Comment by smokeynotes** [comment]
👍
