### ISSUE TITLE
Subscription keeper restart preparation - avalanche

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#124]
# Description

Schedule and execute the Timelock to move the keeper queue bucket current:

```javascript
setProcessingBucket('1', '1659116562');
setProcessingBucket('2', '1659116562');
```

Time:
```
> new Date(1659116562 * 1000)
2022-07-29T17:42:42.000Z
```

# Transaction Target

CaskTimelockController: `0x6821189A4fc9EF5cc00892D207BEc99C56A7425f`

## Timelock Transaction:

scheduleBatch:
* targets: `["0xfA07af9E5835D720b3798a37f716749252F94D71","0xfA07af9E5835D720b3798a37f716749252F94D71"]`
* values: `[0,0]`
* datas: `["0xa76d67b800000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000062e41c12","0xa76d67b800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000062e41c12"]`
* predecesor: `0x0000000000000000000000000000000000000000000000000000000000000000`
* salt: `0x1382e01127f194535688bd02845050a5fdd149f17b6db0379dc4588b3a03fc7f`
* delay: 172801

executeBatch:
* targets: `["0xfA07af9E5835D720b3798a37f716749252F94D71","0xfA07af9E5835D720b3798a37f716749252F94D71"]`
* values: `[0,0]`
* datas: `["0xa76d67b800000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000062e41c12","0xa76d67b800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000062e41c12"]`
* predecesor: `0x0000000000000000000000000000000000000000000000000000000000000000`
* salt: `0x1382e01127f194535688bd02845050a5fdd149f17b6db0379dc4588b3a03fc7f`

# Verification code

`yarn hardhat console --network mainnet_avalanche`

```javascript
subscriptionManager = await ethers.getContract("CaskSubscriptionManager")
data1 = subscriptionManager.interface.encodeFunctionData('setProcessingBucket', ['1', '1659116562'])
data2 = subscriptionManager.interface.encodeFunctionData('setProcessingBucket', ['2', '1659116562'])
```

# Post execution confirmation code

`yarn hardhat console --network mainnet_avalanche`

```javascript
const subscriptionManager = await ethers.getContract("CaskSubscriptionManager");
await subscriptionManager.queuePosition('1');
await subscriptionManager.queuePosition('2');
```

**Comment by masha256** [comment]
nonce 13 created for timelock scheduleBatch

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Timelock Operation hash: `0xe47c504a2f66a4038d9a286d034d10d57b6f11e08400d40bd58f15f97d4c369a`

**Comment by masha256** [comment]
```
> new Date((await timelock.getTimestamp('0xe47c504a2f66a4038d9a286d034d10d57b6f11e08400d40bd58f15f97d4c369a')).toNumber() * 1000)
2022-07-29T17:49:44.000Z
```

**Comment by masha256** [comment]
nonce 14 executed
