### ISSUE TITLE
Set initial subscription protocol parameters - fantom

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#129]
# Description

Set the initial cask protocol parameters as follows:

* `paymentMinValue`: From 0 USDC to 0.50 USDC
* `paymentFeeMin`: From 0 USDC to 0.10 USDC
* `paymentFeeRateMin`: From 0 bps to 140 bps (1.4%)
* `paymentFeeRateMax`: From 0 bps 140 bps (1.4%)
* `stakeTargetFactor`: 0 (not changing)
* `processBucketSize`: 300 seconds (not changing)
*  `processBucketMaxAge`: 3600 seconds (not changing)
* `paymentRetryDelay`:  43200 seconds (not changing)

# Target Contract

`0x17a38EA9257cf899BF9A7F6F507a1445E72F823A`

# Raw transaction data:

`0x9bf4654e000000000000000000000000000000000000000000000000000000000007a12000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000008c000000000000000000000000000000000000000000000000000000000000008c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012c0000000000000000000000000000000000000000000000000000000000000e10000000000000000000000000000000000000000000000000000000000000a8c0`

# Verification code

`yarn hardhat console --network mainnet_fantom`

```javascript
subscriptionManager = await ethers.getContract("CaskSubscriptionManager");
data = subscriptionManager.interface.encodeFunctionData('setParameters', [
    ethers.utils.parseUnits('0.50', 6), // paymentMinValue (USDC)
    ethers.utils.parseUnits('0.10', 6), // paymentFeeMin (USDC)
    ethers.BigNumber.from('140'), // paymentFeeRateMin (bps)
    ethers.BigNumber.from('140'), // paymentFeeRateMax (bps)
    ethers.BigNumber.from('0'), // stakeTargetFactor
    ethers.BigNumber.from('300'), // processBucketSize (seconds)
    ethers.BigNumber.from('3600'), // processBucketMaxAge (seconds)
    ethers.BigNumber.from('43200') // paymentRetryDelay (seconds)
]);
```
Confirmation:
* Confirm `data` matches the proposed transaction data.
* Confirm `subscriptionManager.address` matches the gnosis transaction contract address.

# Post execution confirmation code

`yarn hardhat console --network mainnet_fantom`

```javascript
const subscriptionManager = await ethers.getContract("CaskSubscriptionManager");
ethers.utils.formatUnits(await subscriptionManager.paymentMinValue(), 6);
ethers.utils.formatUnits(await subscriptionManager.paymentFeeMin(), 6);
(await subscriptionManager.paymentFeeRateMin()).toString();
(await subscriptionManager.paymentFeeRateMax()).toString();
(await subscriptionManager.stakeTargetFactor()).toString();
(await subscriptionManager.processBucketSize()).toString();
(await subscriptionManager.processBucketMaxAge()).toString();
(await subscriptionManager.paymentRetryDelay()).toString();
```

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Scheduled and executed safe nonce 2
