### ISSUE TITLE
DCA protocol settings initialization - polygon

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#133]
# Description

Complete DCA settings: 

* `maxSkips`: From 0 to 5
* `dcaFeeBps`: From 0 bps to 60 bps (0.6%)
* `dcaFeeMin`: From 0.00 USDC to 0.50 USDC 
* `dcaMinValue`: From 0.00 USDC to 5.00 USDC 
* `maxPriceFeedAge`: From 0 seconds to 0 seconds (not changing)
* `queueBucketSize`: 3600 seconds to 3600 seconds (not changing)
* `maxQueueAge`: 72000 seconds to 72000 seconds (not changing)

Set fee distributor to DAO multisig: `0x0c91Ec7D8D74A7AffFEe0a53d4447C5b8807F305`

Set asset merkle root: `0x80d530fca5f55c4214be866f950d93ebd9a988a130fc80c69fe074d95ffcbbe8`

# Transaction Batch:

## Settings update
Target: `0xbf6E17f9A48c0033F2211ffA39B7E58772150ace` (CaskDCAManager)
Data: `0x0abe19d90000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000007a12000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e100000000000000000000000000000000000000000000000000000000000011940`

## Set Fee Distributor
Target: `0xbf6E17f9A48c0033F2211ffA39B7E58772150ace` (CaskDCAManager)
Data: `0xccfc2e8d0000000000000000000000000c91ec7d8d74a7afffee0a53d4447c5b8807f305`

## Set Asset Merkle Root
Target: `0x733Ec5A72c38f2f3c75E98b28DffC1885aB04AF1` (CaskDCA)
Data: `0x2ce1757880d530fca5f55c4214be866f950d93ebd9a988a130fc80c69fe074d95ffcbbe8`

# Verification code

`yarn hardhat console --network mainnet_polygon`

```javascript
dcaManager = await ethers.getContract("CaskDCAManager");
setParametersData = dcaManager.interface.encodeFunctionData('setParameters', [
    ethers.BigNumber.from('5'), // maxSkips
    ethers.BigNumber.from('60'), // dcaFeeBps (bps)
    ethers.utils.parseUnits('0.50', 6), // dcaFeeMin (USDC)
    ethers.utils.parseUnits('5.00', 6), // dcaMinValue (USDC)
    ethers.BigNumber.from('0'), // maxPriceFeedAge (seconds)
    ethers.BigNumber.from('3600'), // queueBucketSize (seconds)
    ethers.BigNumber.from('72000') // maxQueueAge (seconds)
]);

setFeeDistributorData = dcaManager.interface.encodeFunctionData('setFeeDistributor', ['0x0c91Ec7D8D74A7AffFEe0a53d4447C5b8807F305']);

dca = await ethers.getContract("CaskDCA");
setAssetsMerkleRootData = dca.interface.encodeFunctionData('setAssetsMerkleRoot', ['0x80d530fca5f55c4214be866f950d93ebd9a988a130fc80c69fe074d95ffcbbe8']);

```

# Post execution confirmation code

`yarn hardhat console --network mainnet_polygon`

```javascript
dcaManager = await ethers.getContract("CaskDCAManager");
(await dcaManager.maxSkips()).toString();
(await dcaManager.dcaFeeBps()).toString();
ethers.utils.formatUnits(await dcaManager.dcaFeeMin(), 6);
ethers.utils.formatUnits(await dcaManager.dcaMinValue(), 6);
(await dcaManager.maxPriceFeedAge()).toString();
(await dcaManager.queueBucketSize()).toString();
(await dcaManager.maxQueueAge()).toString();

await dcaManager.feeDistributor();

await dca.assetsMerkleRoot();
```

**Comment by masha256** [comment]
Created nonce 20

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
executed
