### ISSUE TITLE
DCA protocol update - fantom

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#136]
# Description

Deploy the latest DCA contracts to fantom.

## Contract Implementation Upgrades

`CaskDCAManager` (proxy: ``)
* Old: `0x6821189A4fc9EF5cc00892D207BEc99C56A7425f`
* New: `0xfa3ed790FD1fdC5E15c900D929c2F0527a0eC8b6`

# Transaction Target

DefaultProxyAdmin: `0x20151fF7fDd720b85063D02081aa5B7876aDff7B`

# Transaction List

upgrade
* proxy: `0xfa3ed790FD1fdC5E15c900D929c2F0527a0eC8b6`
* implementation: `0x40036f94054CE5b42fc85D6c84cf94d98f68561A`

# Post execution confirmation code

`yarn hardhat debug:dca --network mainnet_fantom`

Confirmation:
* Confirm `Impl` contract addresses have updated.

**Comment by masha256** [comment]
Created safe txn at nonce 9

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
executed
