### ISSUE TITLE
DCA protocol update - avalanche

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#137]
# Description

Deploy the latest DCA contracts to avalanche.

## Contract Implementation Upgrades

`CaskDCAManager` (proxy: `0xdb78923D5F7381143c16d57E474bCB5c939Df5DE`)
* Old: `0xD87d1F65f768f07a478B93039Dc94903F6517DE8`
* New: `0x60a75B5B7DCa50ad7E0a27802Dc0f0e676006679`

# Transaction Target

DefaultProxyAdmin: `0x0645314c1Afd4d9711d609e3e755265aBaBc95Eb`

# Transaction List

upgrade
* proxy: `0xdb78923D5F7381143c16d57E474bCB5c939Df5DE`
* implementation: `0x60a75B5B7DCa50ad7E0a27802Dc0f0e676006679`

# Post execution confirmation code

`yarn hardhat debug:dca --network mainnet_avalanche`

Confirmation:
* Confirm `Impl` contract addresses have updated.

**Comment by masha256** [comment]
Created safe txn at nonce 20

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
executed
