### ISSUE TITLE
Add fUSDT and DAI as approved assets in vault - fantom

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#142]
# Description

Allow the following assets in the cask vault on fantom:

## fUSDT
* contract: `0x049d68029688eabf473097a2fc38ef61633a3c7a`
* price feed: `0xF64b636c5dFe1d3555A847341cDC449f612307d0`
* depositLimit: 100M
* slippage bps: 10

## DAI
* contract: `0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e`
* price feed: `0x91d5DEFAFfE2854C7D02F50c80FA1fdc8A721e52`
* depositLimit: 100M
* slippage bps: 10

# Transaction

Target: `0x28418B0AB2C00142a865971dcC6a4b1154DaD19E` (CaskTimelockController)

### txn 1 - `allowAsset` for fUSDT
Target: `0xBCcDbB0806Acc914F6746DE592f924B374190710` (CaskVault)
Data: `0x1e377d39000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a000000000000000000000000f64b636c5dfe1d3555a847341cdc449f612307d000000000000000000000000000000000000000000000000000005af3107a4000000000000000000000000000000000000000000000000000000000000000000a`

### txn 2 - `allowAsset` for DAI
Target: `0xBCcDbB0806Acc914F6746DE592f924B374190710` (CaskVault)
Data: `0x1e377d390000000000000000000000008d11ec38a3eb5e956b052f67da8bdc9bef8abf3e00000000000000000000000091d5defaffe2854c7d02f50c80fa1fdc8a721e5200000000000000000000000000000000000000000052b7d2dcc80cd2e4000000000000000000000000000000000000000000000000000000000000000000000a`

## Batch Info
predecessor: `0x0000000000000000000000000000000000000000000000000000000000000000`
salt: `0xe2271f3013b82e285ab9900b2799d6ff776f8079739c2d394788d15fa634d0a4`
delay: `172801`

# Verification code

`yarn hardhat console --network mainnet_fantom`

```javascript
vault = await ethers.getContract("CaskVault");
usdtData = vault.interface.encodeFunctionData('allowAsset', [
    '0x049d68029688eabf473097a2fc38ef61633a3c7a', // asset address
    '0xF64b636c5dFe1d3555A847341cDC449f612307d0', // priceFeed address
    ethers.utils.parseUnits('100000000', 6), // deposit limit
    10 // slippageBps - 0.1%
]);
daiData = vault.interface.encodeFunctionData('allowAsset', [
    '0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e', // asset address
    '0x91d5DEFAFfE2854C7D02F50c80FA1fdc8A721e52', // priceFeed address
    ethers.utils.parseUnits('100000000', 18), // deposit limit
    10 // slippageBps - 0.1%
]);
```
Confirmation:
* Confirm `data` matches the proposed transaction data.
* Confirm `vault.address` matches the transaction target.

# Post execution confirmation code

`yarn hardhat console --network mainnet_fantom`

```javascript
vault = await ethers.getContract("CaskVault");
await vault.getAsset('0x049d68029688eabf473097a2fc38ef61633a3c7a');
await vault.getAsset('0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e');
```
Confirm `allowed` is `true` and all parameters match the desired settings.

**Comment by masha256** [comment]
Created safe txn nonce 10 & 11

**Comment by masha256** [comment]
Scheduled safe txn at nonce 12

**Comment by masha256** [comment]
Timelock operation: `0x4a8f0456fb89b42de6f22ab687dd5a043289464a70a3312c421b13a8190528db`

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Timelock executeBatch safe nonce 14 created

**Comment by masha256** [comment]
executed
