### ISSUE TITLE
Remove old DCAManager/P2PManager and add new DCAManager to cask vault allowed protocols - avalanche

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#146]
# Description

Remove the old CaskDCAManager from the cask vault allowed protocols and add the new CaskDCAManager to the cask vault allowed protocols.

* Old CaskDCAManager: `0xdb78923D5F7381143c16d57E474bCB5c939Df5DE`
* Old CaskP2PManager: `0x781a5958954a10066feB7B3E94D22D9F8c163e8b`
* New CaskDCAManager: `0x4898D1e6d9761B4215901817FBe9F12750238882`

# Transaction

Target: `0x6821189A4fc9EF5cc00892D207BEc99C56A7425f` (CaskTimelockController)

## txn 1 - `removeProtocol` for old CaskDCAManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x18ff5768000000000000000000000000db78923d5f7381143c16d57e474bcb5c939df5de`

## txn 2 - `removeProtocol` for old CaskP2PManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x18ff5768000000000000000000000000781a5958954a10066feb7b3e94d22d9f8c163e8b`

## txn 3 - `addProtocol` for new CaskDCAManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x771d4c280000000000000000000000004898d1e6d9761b4215901817fbe9f12750238882`

## Batch Info
predecessor: `0x0000000000000000000000000000000000000000000000000000000000000000`
salt: `0xbf9a53741abf90ba045607dec1cce831f7d46cde45744d9849a2016a5bba666a`
delay: `172801`

# Verification code

`yarn hardhat console --network mainnet_avalanche`

```javascript
vault = await ethers.getContract("CaskVault");
data1 = vault.interface.encodeFunctionData('removeProtocol', ['0xdb78923D5F7381143c16d57E474bCB5c939Df5DE']);
data2 = vault.interface.encodeFunctionData('removeProtocol', ['0x781a5958954a10066feB7B3E94D22D9F8c163e8b']);
data3 = vault.interface.encodeFunctionData('addProtocol', ['0x4898D1e6d9761B4215901817FBe9F12750238882']);

```
Confirmation:
* Confirm `dataX` matches the proposed transaction data.
* Confirm `vault.address` matches the transaction target.

# Post execution confirmation code

`yarn hardhat console --network mainnet_avalanche`

```javascript
vault = await ethers.getContract("CaskVault");
await vault.protocols(0); // CaskSubscriptionManager
await vault.protocols(1); // New CaskDCAManager
await vault.protocols(2); // Error - no 3rd protocol
```

**Comment by masha256** [comment]
Created schedule txn at nonce 23

**Comment by masha256** [comment]
Timelock operation: `0xa118f1cfe9580c18371f4ea5868e227b242b2d25955183a1cdf53c6f03e99d80`

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Timelock executeBatch safe nonce 24 created

**Comment by masha256** [comment]
executed
