### ISSUE TITLE
Add protocols to cask vault - aurora

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#148]
# Description

Allow the following protocols to the cask vault on aurora:

* `0x331979A83644574E56035E4b43d3ca68Ce793918` (CaskSubscriptionManager)
* `0x83aA6a992Ff3ef3766679Cc90E8C60a04afcC171` (CaskDCAManager)
* `0xb8A52a086262E1d6c7494bDCb824f884f41FC5f8` (CaskP2PManager) 

# Transaction

Target: `0x733Ec5A72c38f2f3c75E98b28DffC1885aB04AF1` (CaskTimelockController)

## txn 1 - `addProtocol` for CaskSubscriptionManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x771d4c28000000000000000000000000331979a83644574e56035e4b43d3ca68ce793918`

## txn 2 - `addProtocol` for CaskDCAManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x771d4c2800000000000000000000000083aa6a992ff3ef3766679cc90e8c60a04afcc171`

## txn 3 - `addProtocol` for CaskP2PManager
Target: `0x3b2b4b547dAEEbf3A703288CB43650f0F287b9ff`
Data: `0x771d4c28000000000000000000000000b8a52a086262e1d6c7494bdcb824f884f41fc5f8`

## Batch Info
predecessor: `0x0000000000000000000000000000000000000000000000000000000000000000`
salt: `0xac917256ef65e17358c5b1cb5ffbc336d9f7f89613d6969b86ab5c6f06ac1a6d`
delay: `172801`

# Verification code

`yarn hardhat console --network mainnet_aurora`

```javascript
vault = await ethers.getContract("CaskVault");
dcaManager = await ethers.getContract("CaskDCAManager");
p2pManager = await ethers.getContract("CaskP2PManager");
subscriptionManager = await ethers.getContract("CaskSubscriptionManager");

data = vault.interface.encodeFunctionData('addProtocol', [subscriptionManager.address]);
data = vault.interface.encodeFunctionData('addProtocol', [dcaManager.address]);
data = vault.interface.encodeFunctionData('addProtocol', [p2pManager.address]);
```
Confirmation:
* Confirm `data` matches the proposed transaction data.
* Confirm `vault.address` matches the transaction target.

# Post execution confirmation code

`yarn hardhat console --network mainnet_aurora`

```javascript
vault = await ethers.getContract("CaskVault");
await vault.getProtocol(0); // address of CaskSubscriptionManager
await vault.getProtocol(1); // address of CaskDCAManager
await vault.getProtocol(2); // address of CaskP2PManager
await vault.getProtocol(3); // error - only 3 protocols
```

**Comment by masha256** [comment]
Scheduled timelock gnosis txn 12

**Comment by masha256** [comment]
Timelock operation: `0x77f5a96a90fc31daa753a2142083f49b423965551c46762bcc427ed071784d2a`

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Timelock executeBatch safe nonce 14 created

**Comment by masha256** [comment]
executed
