### ISSUE TITLE
Add protocols to cask vault - fantom

### ISSUE THREAD

**Issue by masha256** [CaskProtocol/cask-contracts#149]
# Description

Allow the following protocols to the cask vault on fantom:

* `0x17a38EA9257cf899BF9A7F6F507a1445E72F823A` (CaskSubscriptionManager)
* `0xfa3ed790FD1fdC5E15c900D929c2F0527a0eC8b6` (CaskDCAManager)
* `0x8c4E2551542f399Af1576e9c194ea257Dcb7D926` (CaskP2PManager) 

# Transaction

Target: `0x28418B0AB2C00142a865971dcC6a4b1154DaD19E` (CaskTimelockController)

## txn 1 - `addProtocol` for CaskSubscriptionManager
Target: `0xBCcDbB0806Acc914F6746DE592f924B374190710`
Data: `0x771d4c2800000000000000000000000017a38ea9257cf899bf9a7f6f507a1445e72f823a`

## txn 2 - `addProtocol` for CaskDCAManager
Target: `0xBCcDbB0806Acc914F6746DE592f924B374190710`
Data: `0x771d4c28000000000000000000000000fa3ed790fd1fdc5e15c900d929c2f0527a0ec8b6`

## txn 3 - `addProtocol` for CaskP2PManager
Target: `0xBCcDbB0806Acc914F6746DE592f924B374190710`
Data: `0x771d4c280000000000000000000000008c4e2551542f399af1576e9c194ea257dcb7d926`

## Batch Info
predecessor: `0x0000000000000000000000000000000000000000000000000000000000000000`
salt: `0x6d09371be1762eb8ad1484eb93d29af85cc40da422a6b19d6b10048dd07a286f`
delay: `172801`

# Verification code

`yarn hardhat console --network mainnet_fantom`

```javascript
vault = await ethers.getContract("CaskVault");
dcaManager = await ethers.getContract("CaskDCAManager");
p2pManager = await ethers.getContract("CaskP2PManager");
subscriptionManager = await ethers.getContract("CaskSubscriptionManager");

data = vault.interface.encodeFunctionData('addProtocol', [subscriptionManager.address]);
data = vault.interface.encodeFunctionData('addProtocol', [dcaManager.address]);
data = vault.interface.encodeFunctionData('addProtocol', [p2pManager.address]);
```
Confirmation:
* Confirm `data` matches the proposed transaction data.
* Confirm `vault.address` matches the transaction target.

# Post execution confirmation code

`yarn hardhat console --network mainnet_fantom`

```javascript
vault = await ethers.getContract("CaskVault");
await vault.getProtocol(0); // address of CaskSubscriptionManager
await vault.getProtocol(1); // address of CaskDCAManager
await vault.getProtocol(2); // address of CaskP2PManager
await vault.getProtocol(3); // error - only 3 protocols
```

**Comment by masha256** [comment]
Scheduled timelock gnosis txn 13

**Comment by masha256** [comment]
Timelock operation: `0xa2f27126f1385a6b491ae4740574068d7c81288f0ae24ee1f5f6b1b139fb3162`

**Comment by smokeynotes** [comment]
👍

**Comment by masha256** [comment]
Created executeBatch safe nonce 15

**Comment by masha256** [comment]
executed
